bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:10049
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: TeachingResearch
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: nguyendangminh03@gmail.com
    password: 'nmfr pmus pazp emai'
    port: '587'
application:
  security:
    jwt:
      secret-key: 531c7c9f715b0e4b92d14a0f9599a3fa1e91cb83d7836a34ec0e030ecedb218d
      expiration: 86400000 # 1 day
  media-directory: "/data/media/"
