bezkoder:
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://172.22.0.0
spring:
  datasource:
    url: jdbc:postgresql://172.22.0.0:5432/teaching_research
    username: postgres
    password: dangminh49
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: TeachingResearch
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
application:
  security:
    jwt:
      secret-key: 531c7c9f715b0e4b92d14a0f9599a3fa1e91cb83d7836a34ec0e030ecedb218d
      expiration: 86400000 # 1 day
  media-directory: "D:\\media\\"
