name: Build on DockerHub and Deploy to home server
on:
  push:
    branches:
      - develop
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
#  ZEROTIER_NETWORK_ID: ${{ secrets.ZEROTIER_NETWORK_ID }}
#  ZEROTIER_CENTRAL_TOKEN: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
  HOST_IP_ADDRESS: ${{ secrets.HOST_IP_ADDRESS }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'adopt'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: monkeydminh49/research-api:1.0
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      #
      #    - name: copy file via ssh password
      #      uses: appleboy/scp-action@v0.1.7
      #      with:
      #        host: ${{ env.HOST_IP_ADDRESS }}
      #        username: ${{ env.SSH_USERNAME }}
      #        password: ${{ env.SSH_PASSWORD }}
      #        port: 22
      #        source: "./docker-compose.yaml"
      #        target: "/home/minh/dangminh/ltw_quiz/"
      #
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST_IP_ADDRESS }}
          username: ${{ env.SSH_USERNAME }}
          password: ${{ env.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${{ env.SSH_PASSWORD }} | sudo -S docker-compose down -v
            echo ${{ env.SSH_PASSWORD }} | sudo -S docker image rm 'monkeydminh49/research-api:1.0'
            echo ${{ env.SSH_PASSWORD }} | sudo -S docker-compose up -d